spring:
  datasource:
    username: root
    password: srivatsan
    url: jdbc:mysql://localhost:3306/test
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update 
    
  application:
    name: loan-application-service
server:
  port: 4040    